### ISSUE TITLE
Deprecate rollup-plugin-inject-process-env in favour of @tmaxmax/rollup-plugin-inject-process-env

### ISSUE THREAD

**Issue by jwanner83** [badcafe/rollup-plugin-inject-process-env#21]
Hey, thank you for your plugin, I really appreciate the work.
I saw that there are currently two versions of this plugin available on npmjs.com. 

@tmaxmax/rollup-plugin-inject-process-env - Version 1.3.3 - Published 9 months ago
https://www.npmjs.com/package/@tmaxmax/rollup-plugin-inject-process-env

rollup-plugin-inject-process-env - Version 1.3.1 - Published 10 months ago
https://www.npmjs.com/package/rollup-plugin-inject-process-env

Wouldn't it be good to [mark the older one as deprecated](https://docs.npmjs.com/cli/v7/commands/npm-deprecate) and add something to the readme stating that the new place for the plugin is beneath @tmaxmax? Or is there a reason that there are two versions arround?

**Comment by tmaxmax** [comment]
Hi there!

I'm not associated with this project actually, I did some edits to the plugin because in the original form it would break my bundle when running on older browsers. My version also includes a globalThis polyfill inside by default because including it separately wouldn't work either in my build configuration.

You probably don't need my version if the original works fine for you.

Either way, the original version is this one, not mine. I could make a PR though if the changes are deemed useful by the maintainers.

**Comment by jwanner83** [comment]
Hey @tmaxmax :) Now I see. 

I think the main thing that confused me, was the repository URL in the https://www.npmjs.com/package/@tmaxmax/rollup-plugin-inject-process-env package, which pointed to this repo instead of your forked one (https://github.com/tmaxmax/rollup-plugin-inject-process-env), as well as the nearly identical README.md file. 

If you've got some time on your hand, maybe you could change these things, but if not, no worries :)  

Either way, I will close this issue now. Thanks for your response 👍
